apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "api-service.fullname" . }}
  labels:
    app: {{ template "api-service.name" . }}
    chart: {{ template "api-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/db/mongo/{{ template "api-service.fullname" . }}