apiVersion: v1
kind: Service
metadata:
  name: {{ template "fic-demo-api-service.fullname" . }}
  labels:
    app: {{ template "fic-demo-api-service.name" . }}
    chart: {{ template "fic-demo-api-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "fic-demo-api-service.name" . }}
    release: {{ .Release.Name }}
